// <auto-generated />
using System;
using MeuControle.Infra.Contextos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MeuControle.Infra.Migrations
{
    [DbContext(typeof(ContextoDados))]
    [Migration("20201122203146_AgoravaiJuro6")]
    partial class AgoravaiJuro6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("MeuControle.Dominio.Entidades.LancamentoConta", b =>
                {
                    b.Property<Guid>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CodigoPlanoConta")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CodigoUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("date");

                    b.Property<string>("Operacao")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoPlanoConta");

                    b.HasIndex("CodigoUsuario");

                    b.ToTable("LancamentosContas");
                });

            modelBuilder.Entity("MeuControle.Dominio.Entidades.PlanoConta", b =>
                {
                    b.Property<Guid>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CodigoUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Operacao")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<Guid?>("UsuarioCodigo")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Codigo");

                    b.HasIndex("UsuarioCodigo");

                    b.ToTable("PlanosContas");
                });

            modelBuilder.Entity("MeuControle.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Senha")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Codigo");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("MeuControle.Dominio.Entidades.LancamentoConta", b =>
                {
                    b.HasOne("MeuControle.Dominio.Entidades.PlanoConta", "PlanoConta")
                        .WithMany("LancamentosContas")
                        .HasForeignKey("CodigoPlanoConta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeuControle.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("LancamentosContas")
                        .HasForeignKey("CodigoUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanoConta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MeuControle.Dominio.Entidades.PlanoConta", b =>
                {
                    b.HasOne("MeuControle.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("PlanosContas")
                        .HasForeignKey("UsuarioCodigo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MeuControle.Dominio.Entidades.PlanoConta", b =>
                {
                    b.Navigation("LancamentosContas");
                });

            modelBuilder.Entity("MeuControle.Dominio.Entidades.Usuario", b =>
                {
                    b.Navigation("LancamentosContas");

                    b.Navigation("PlanosContas");
                });
#pragma warning restore 612, 618
        }
    }
}
